### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by einarhuseby** [zefoy/ngx-quill-wrapper#2]
Is there a way/how to add 3rd party quill modules?

Example modules:
- [quill-image-resize](/kensnyder/quill-image-resize-module)
- [quill-focus](/amka/quill-focus/)
- [quill-image-drop-module](/kensnyder/quill-image-drop-module)
- [quill-image-url-drop-module](/riencroonenborghs/quill-image-url-drop-module)
- [quill-magic-url](/visualjerk/quill-magic-url)

**Comment by sconix** [comment]
I think atm no, but I can make a new release with support for registering modules.

**Comment by einarhuseby** [comment]
Thanks @sconix, that would be very helpful!

**Comment by sconix** [comment]
Sorry, I just now opened the links that you gave and it looks like the module registration is done in a way that there is no easy way in Angular to register 3rd party modules. Registering does seem to need the global Quill object and I don't know how that could be done withing a library. Depending on your build system you might be able to do it manually, but not sure.

I will anyway see if there is a some way to do this, but might be that there is none provided by the Angular.

**Comment by sconix** [comment]
I found at least one way to do this, but there can not be a way to do it so that this library would register the modules. I will post instructions how to do this with angular-cli projects soon once I have verified it to work.

**Comment by einarhuseby** [comment]
Thanks!

**Comment by sconix** [comment]
I am going to make a 5.3.4 release that supports using a global Quill. This means that you can load the Quill script globally by adding it to the angular-cli.json scripts section (in addition with the 3rd party module scripts). This way you can do this in you application code:

declare var Quill: any;
declare var Focus: any;

Quill.register('modules/focus', Focus);

When angular 6 is released I plan to add lazy loading of the Quill into this wrapper and then I am able to implement proper support for loading these custom modules. But until that the above should work with the 5.3.4 version of this library.

**Comment by sconix** [comment]
I found a better way to do this. So I will release 5.3.5 which takes care of registering the module and there is no need to globally load the Quill library. I will update the README to have information about using custom modules.
