### ISSUE TITLE
Paste not working in safari, ios

### ISSUE THREAD

**Issue by haneyman** [zefoy/ngx-quill-wrapper#3]
Hello,

I am using this component in an Ionic 3 / Cordova / Angular 5 application.  The paste works fine on a web page using chrome but NOT safari, and when this is deployed to an iPhone the paste does not work either.  The valueChange and contentChange events are being triggered but they don't show the clipboard text that was pasted.  

Any idea what might be the issue?

**Comment by sconix** [comment]
I would suspect that there is a bug in Quill and not in this wrapper, but I can verify that next week. Have you checked if Quill has an such issue already?

**Comment by haneyman** [comment]
I've done a lot of searching and no reference to this issue.  I know the angular framework recognizes the paste event but it's getting eaten somewhere.

**Comment by haneyman** [comment]
I found the issue, it was in my CSS.  I had put ".ql-editor { -webkit-user-select: text; }" which is needed for webkit to edit the text.  By moving that CSS to the <quill it fixed the paste issue.  Thanks for the quick response.
